/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DesignUI;

import Models.Application;
import Models.Room;
import Models.Student;
import Utils.ApplicationHandling;
import Utils.RoomHandling;
import Utils.PopUpWindow;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JTextField;

/**
 *
 * @author KZ
 */
public class ApplicationST extends javax.swing.JPanel {

    private static ArrayList<Room> availableRooms;
    private static Room selectedRoom;
    private static String selectedRoomType;
    private static Student currentUser;
    private static Application currentUserApplication;
    private static Room currentUserRoom;
    
    /**
     * Creates new form ApplicationST
     */
    public ApplicationST() {
        initData();
        initComponents();
        if (currentUserRoom == null) {
            appliedPanel.setVisible(false);
            notAppliedPanel.setVisible(true);
            confirmBtn.setVisible(true);
        } else {
            notAppliedPanel.setVisible(false);
            confirmBtn.setVisible(false);
            appliedPanel.setVisible(true);
        }
    }
    
    private static void initData() {
        selectedRoomType = null;
        availableRooms = RoomHandling.getAvailableRooms();
        currentUser = Login.getCurrentUser();
        currentUserApplication = ApplicationHandling.getCurrentStudentApplication(Login.getCurrentUser());
        currentUserRoom = currentUserApplication.getRoom();
    }
    
    public static void setSelectedRoom() {
        if (availableRooms.isEmpty()) {
            PopUpWindow.showErrorMessage("Sorry, there are no available rooms at the moment.", "Unavailable");
        } else {
            // TODO: change to set the first selected room type that is available
            selectedRoom = availableRooms.get(0);
            jLabel2.setText(selectedRoom.getRoomID());
        }
    }
    
    public static Room getSelectedRoom() {
        return selectedRoom;
    }
    
    public static void setSelectedRoomType(String selectedRoomType) {
        ApplicationST.selectedRoomType = selectedRoomType;
        jLabel4.setText(selectedRoomType);
    }
    
    public static Student getCurrentUser() {
        return currentUser;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        appliedPanel = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        notAppliedPanel = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        roomDetailsSection = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentDetailsSection = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        emerContactSection = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        warningLabel = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Apply");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1058, 10));

        appliedPanel.setBackground(new java.awt.Color(255, 255, 255));
        appliedPanel.setLayout(new java.awt.GridLayout(4, 2, 0, 30));

        jLabel53.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 51));
        jLabel53.setText("Application Status");
        appliedPanel.add(jLabel53);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Pending");
        if (jLabel10.getText().equals("Pending")) {
            jLabel10.setForeground(Color.BLUE);
        } else if (jLabel10.getText().equals("Rejected")) {
            jLabel10.setForeground(Color.RED);
        } else {
            jLabel10.setForeground(Color.GREEN);
        }
        appliedPanel.add(jLabel10);

        jLabel52.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));
        jLabel52.setText("Room Details");
        appliedPanel.add(jLabel52);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        appliedPanel.add(jPanel6);

        jLabel54.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 51));
        jLabel54.setText("Room Number");
        appliedPanel.add(jLabel54);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("R001");
        appliedPanel.add(jLabel11);

        jLabel55.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(51, 51, 51));
        jLabel55.setText("Room Type");
        appliedPanel.add(jLabel55);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Single");
        appliedPanel.add(jLabel12);

        add(appliedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1040, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomDetailsSection.setBackground(new java.awt.Color(255, 255, 255));
        roomDetailsSection.setLayout(new java.awt.GridLayout(3, 2, 0, 30));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Room Details");
        roomDetailsSection.add(jLabel49);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        roomDetailsSection.add(jPanel1);

        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("Room Type");
        roomDetailsSection.add(jLabel48);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        System.out.println(selectedRoomType);
        jLabel4.setText("N/A");
        roomDetailsSection.add(jLabel4);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("Room Number");
        roomDetailsSection.add(jLabel47);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("N/A");
        roomDetailsSection.add(jLabel2);

        jPanel2.add(roomDetailsSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 930, 160));

        studentDetailsSection.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.setLayout(new java.awt.GridLayout(11, 2, 0, 30));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("Student Details");
        studentDetailsSection.add(jLabel50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        studentDetailsSection.add(jPanel3);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Full Name");
        studentDetailsSection.add(jLabel19);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(currentUser.getName().replace("_", " "));
        studentDetailsSection.add(jLabel5);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Email");
        studentDetailsSection.add(jLabel35);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(currentUser.getEmail());
        studentDetailsSection.add(jLabel6);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Gender");
        studentDetailsSection.add(jLabel21);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(currentUser.getGender());
        studentDetailsSection.add(jLabel7);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("HP No");
        studentDetailsSection.add(jLabel33);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText(currentUser.getPhoneNo());
        studentDetailsSection.add(jLabel8);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("IC/Passport Number");
        studentDetailsSection.add(jLabel23);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText(currentUser.getNRIC());
        studentDetailsSection.add(jLabel9);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("<html>Nationality<font color='red'>*</font></html>");
        studentDetailsSection.add(jLabel27);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(jTextField1);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Race");
        studentDetailsSection.add(jLabel29);

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(jTextField2);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Religion");
        studentDetailsSection.add(jLabel31);

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(jTextField3);

        jLabel37.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("<html>Permanent Address<font color='red'>*</font></html>");
        studentDetailsSection.add(jLabel37);

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(jTextField4);

        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Medical Condition (if any)");
        studentDetailsSection.add(jLabel39);

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(jTextField5);

        jPanel2.add(studentDetailsSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 930, 630));

        emerContactSection.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.setLayout(new java.awt.GridLayout(4, 2, 0, 30));

        jLabel51.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        jLabel51.setText("Emergency Contact");
        emerContactSection.add(jLabel51);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        emerContactSection.add(jPanel4);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setText("<html>Emergency Contact Name<font color='red'>*</font></html>");
        emerContactSection.add(jLabel44);

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.add(jTextField6);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setText("<html>Emergency Contact Relationship<font color='red'>*</font></html>");
        emerContactSection.add(jLabel43);

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.add(jTextField7);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("<html>Emergency Contact Number<font color='red'>*</font></html>");
        emerContactSection.add(jLabel41);

        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.add(jTextField8);

        jPanel2.add(emerContactSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 870, 930, 250));

        warningLabel.setText("<html><font color='red'>Please fill in all the required (*) fields</font></html>");
        jPanel2.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        notAppliedPanel.setViewportView(jPanel2);

        add(notAppliedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1040, 460));

        confirmBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.setToolTipText("");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, -1, -1));
        if (currentUserRoom != null) {
            warningLabel.setVisible(false);
        }
    }// </editor-fold>//GEN-END:initComponents

    private boolean requiredFieldsValid() {
        boolean valid = true;
        
        if (jTextField1.getText().isBlank()) {
            valid = false;
        }
        if (jTextField4.getText().isBlank()) {
            valid = false;
        }
        if (jTextField6.getText().isBlank()) {
            valid = false;
        }
        if (jTextField7.getText().isBlank()) {
            valid = false;
        }
        if (jTextField8.getText().isBlank()) {
            valid = false;
        }
        
        return valid;
    }
    
    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        if (selectedRoomType == null) {
            PopUpWindow.showErrorMessage("Please select a room type in the Rooms page first.", "Error");
            HostelST.getCardManager().show(HostelST.getMainPanel(), "rooms");
        } else if (requiredFieldsValid() == false) {
            PopUpWindow.showErrorMessage("Please fill in all the required(*) fields.", "Error");
        }
        HostelST.getCardManager().show(HostelST.getMainPanel(), "T&C");
    }//GEN-LAST:event_confirmBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appliedPanel;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JPanel emerContactSection;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel10;
    private static javax.swing.JLabel jLabel11;
    private static javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JScrollPane notAppliedPanel;
    private javax.swing.JPanel roomDetailsSection;
    private javax.swing.JPanel studentDetailsSection;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
