/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DesignUI;

import Models.Room;
import Models.Student;
import Utils.Config;
import Utils.PopUpWindow;
import static Utils.Validator.validateApplicationInputDate;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author KZ
 */
public class BeforeApplyST extends javax.swing.JPanel {

    private static Room room;
    private static Student student;
    private static final String DATE_INPUT_FORMAT = Config.dateFormats.ST_APPLICATION_DATE_INPUT.getFormat();

    private static HashMap<JLabel, JTextField> requiredFields;

    /**
     * Creates new form BeforeApplyST
     */
    public BeforeApplyST() {
        initData();
        initComponents();
        setRequiredFields();
        if (!student.getNationality().equals(Config.NOT_APPLICABLE)) {
            fillFields();
        }
    }

    private void initData() {
        room = HostelST.getSelectedRoom();
        student = HostelST.getCurrentUser();
    }
    
    private void fillFields() {
        nationalityField.setText(student.getNationality().replace("_", " "));
        raceField.setText(student.getRace().replace("_", " "));
        religionField.setText(student.getReligion().replace("_", " "));
        addressField.setText(student.getPermanentAddress().replace("_", " "));
        medCondField.setText(student.getMedicalCondition().replace("_", " "));
        emerContactNameField.setText(student.getEmerContactName().replace("_", " "));
        emerContactRelationshipField.setText(student.getEmerContactRelationship().replace("_", " "));
        emerContactNoField.setText(student.getEmerContactNo());
    }

    private void setRequiredFields() {
        requiredFields = new HashMap<>();
        requiredFields.put(startDateLabel, startDateField);
        requiredFields.put(nationalityLabel, nationalityField);
        requiredFields.put(addressLabel, addressField);
        requiredFields.put(emerContactNameLabel, emerContactNameField);
        requiredFields.put(emerContactRelationshipLabel, emerContactRelationshipField);
        requiredFields.put(emerContactNoLabel, emerContactNoField);

        for (JLabel label : requiredFields.keySet()) {
            String currentText = label.getText();
            label.setText("<html>" + currentText + "<font color='red'>*</font></html>");
        }
    }

    public static HashMap<String, String> getInputForm() {
        HashMap<String, String> buffer = new HashMap<>();
        buffer.put("roomType", roomTypeLabel.getText());
        buffer.put("roomNumber", roomNumLabel.getText());
        buffer.put("checkInDate", startDateField.getText());
        buffer.put("periodOfStay", "" + stayPeriodComboBox.getSelectedIndex());
        buffer.put("fullName", nameLabel.getText());
        buffer.put("email", emailLabel.getText());
        buffer.put("gender", genderLabel.getText());
        buffer.put("phoneNo", hpNoLabel.getText());
        buffer.put("NRIC", NRICLabel.getText());
        buffer.put("nationality", nationalityField.getText());
        if (raceField.getText().isBlank()) {
            buffer.put("race", Config.NOT_APPLICABLE);
        } else {
            buffer.put("race", raceField.getText());
        }
        if (religionField.getText().isBlank()) {
            buffer.put("religion", Config.NOT_APPLICABLE);
        } else {
            buffer.put("religion", religionField.getText());
        }
        buffer.put("address", addressField.getText());
        if (medCondField.getText().isBlank()) {
            buffer.put("medicalCondition", Config.NOT_APPLICABLE);
        } else {
            buffer.put("medicalCondition", medCondField.getText());
        }
        buffer.put("emerContactName", emerContactNameField.getText());
        buffer.put("emerContactRelationship", emerContactRelationshipField.getText());
        buffer.put("emerContactNo", emerContactNoField.getText());
        return buffer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        roomDetailsSection = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        roomTypeLabel = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        roomNumLabel = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        roomNumLabel1 = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        startDateField = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        stayPeriodComboBox = new javax.swing.JComboBox<>();
        studentDetailsSection = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        hpNoLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        NRICLabel = new javax.swing.JLabel();
        nationalityLabel = new javax.swing.JLabel();
        nationalityField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        raceField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        religionField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        medCondField = new javax.swing.JTextField();
        emerContactSection = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        emerContactNameLabel = new javax.swing.JLabel();
        emerContactNameField = new javax.swing.JTextField();
        emerContactRelationshipLabel = new javax.swing.JLabel();
        emerContactRelationshipField = new javax.swing.JTextField();
        emerContactNoLabel = new javax.swing.JLabel();
        emerContactNoField = new javax.swing.JTextField();
        warningLabel = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomDetailsSection.setBackground(new java.awt.Color(255, 255, 255));
        roomDetailsSection.setLayout(new java.awt.GridLayout(6, 2, 0, 30));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 51, 51));
        jLabel49.setText("Room Details");
        roomDetailsSection.add(jLabel49);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        roomDetailsSection.add(jPanel1);

        jLabel48.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 51, 51));
        jLabel48.setText("Room Type");
        roomDetailsSection.add(jLabel48);

        roomTypeLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        roomTypeLabel.setText(room.getRoomType().getTypeName());
        roomDetailsSection.add(roomTypeLabel);

        jLabel47.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 51, 51));
        jLabel47.setText("Room Number");
        roomDetailsSection.add(jLabel47);

        roomNumLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomNumLabel.setForeground(new java.awt.Color(0, 0, 0));
        roomNumLabel.setText(room.getRoomID());
        roomDetailsSection.add(roomNumLabel);

        jLabel52.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 51));
        jLabel52.setText("Floor");
        roomDetailsSection.add(jLabel52);

        roomNumLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        roomNumLabel1.setForeground(new java.awt.Color(0, 0, 0));
        roomNumLabel1.setText(String.valueOf(room.getRoomID().charAt(1)));
        roomDetailsSection.add(roomNumLabel1);

        startDateLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(51, 51, 51));
        startDateLabel.setText("Check-In Date (DD-MM-YYYY)");
        roomDetailsSection.add(startDateLabel);

        startDateField.setBackground(new java.awt.Color(255, 255, 255));
        roomDetailsSection.add(startDateField);

        jLabel57.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(51, 51, 51));
        jLabel57.setText("Period of Stay");
        roomDetailsSection.add(jLabel57);

        stayPeriodComboBox.setBackground(new java.awt.Color(255, 255, 255));
        stayPeriodComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        stayPeriodComboBox.setForeground(new java.awt.Color(0, 0, 0));
        stayPeriodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 year", "2 years", "3 years", "4 years", "5 years" }));
        roomDetailsSection.add(stayPeriodComboBox);

        jPanel2.add(roomDetailsSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 930, 350));

        studentDetailsSection.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.setLayout(new java.awt.GridLayout(11, 2, 0, 30));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 51, 51));
        jLabel50.setText("Student Details");
        studentDetailsSection.add(jLabel50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        studentDetailsSection.add(jPanel3);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Full Name");
        studentDetailsSection.add(jLabel19);

        nameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 0, 0));
        nameLabel.setText(student.getName().replace("_", " "));
        studentDetailsSection.add(nameLabel);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Email");
        studentDetailsSection.add(jLabel35);

        emailLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText(student.getEmail());
        studentDetailsSection.add(emailLabel);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Gender");
        studentDetailsSection.add(jLabel21);

        genderLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(0, 0, 0));
        genderLabel.setText(student.getGender());
        studentDetailsSection.add(genderLabel);

        jLabel33.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("HP No");
        studentDetailsSection.add(jLabel33);

        hpNoLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        hpNoLabel.setForeground(new java.awt.Color(0, 0, 0));
        hpNoLabel.setText(student.getPhoneNo());
        studentDetailsSection.add(hpNoLabel);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("IC/Passport Number");
        studentDetailsSection.add(jLabel23);

        NRICLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NRICLabel.setForeground(new java.awt.Color(0, 0, 0));
        NRICLabel.setText(student.getNRIC());
        studentDetailsSection.add(NRICLabel);

        nationalityLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nationalityLabel.setForeground(new java.awt.Color(51, 51, 51));
        nationalityLabel.setText("Nationality");
        studentDetailsSection.add(nationalityLabel);

        nationalityField.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(nationalityField);

        jLabel29.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Race");
        studentDetailsSection.add(jLabel29);

        raceField.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(raceField);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Religion");
        studentDetailsSection.add(jLabel31);

        religionField.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(religionField);

        addressLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(51, 51, 51));
        addressLabel.setText("Permanent Address");
        studentDetailsSection.add(addressLabel);

        addressField.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(addressField);

        jLabel39.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Medical Condition (if any)");
        studentDetailsSection.add(jLabel39);

        medCondField.setBackground(new java.awt.Color(255, 255, 255));
        studentDetailsSection.add(medCondField);

        jPanel2.add(studentDetailsSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 930, 630));

        emerContactSection.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.setLayout(new java.awt.GridLayout(4, 2, 0, 30));

        jLabel51.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 51));
        jLabel51.setText("Emergency Contact");
        emerContactSection.add(jLabel51);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        emerContactSection.add(jPanel4);

        emerContactNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emerContactNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        emerContactNameLabel.setText("Emergency Contact Name");
        emerContactSection.add(emerContactNameLabel);

        emerContactNameField.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.add(emerContactNameField);

        emerContactRelationshipLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emerContactRelationshipLabel.setForeground(new java.awt.Color(51, 51, 51));
        emerContactRelationshipLabel.setText("Emergency Contact Relationship");
        emerContactSection.add(emerContactRelationshipLabel);

        emerContactRelationshipField.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.add(emerContactRelationshipField);

        emerContactNoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        emerContactNoLabel.setForeground(new java.awt.Color(51, 51, 51));
        emerContactNoLabel.setText("Emergency Contact Number");
        emerContactSection.add(emerContactNoLabel);

        emerContactNoField.setBackground(new java.awt.Color(255, 255, 255));
        emerContactSection.add(emerContactNoField);

        jPanel2.add(emerContactSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1060, 930, 250));

        warningLabel.setText("<html><font color='red'>Please fill in all the required (*) fields</font></html>");
        jPanel2.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        scrollPane.setViewportView(jPanel2);

        add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1047, 450));

        confirmBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.setToolTipText("");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        add(confirmBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));
        if (DesignUI.HostelST.getSelectedRoom() == null) {
            confirmBtn.setVisible(true);
        }
    }// </editor-fold>//GEN-END:initComponents

    private boolean requiredFieldsValid() {
        for (JTextField field : requiredFields.values()) {
            if (field.getText().isBlank()) {
                return false;
            }
        }
        return true;
    }

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if (HostelST.getSelectedRoom() == null) {
            PopUpWindow.showErrorMessage("Please select a room type in the Rooms page first.", "Error");
            HostelST.showRooms();
        } else if (requiredFieldsValid() == false) {
            PopUpWindow.showErrorMessage("Please fill in all the required(*) fields.", "Error");
        } else if (validateApplicationInputDate(startDateField.getText(), DATE_INPUT_FORMAT) == null) {
            PopUpWindow.showErrorMessage("Invalid date or format.", "Error");
        } else {
            HostelST.showTnC();
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel NRICLabel;
    private static javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton confirmBtn;
    private static javax.swing.JLabel emailLabel;
    private static javax.swing.JTextField emerContactNameField;
    private javax.swing.JLabel emerContactNameLabel;
    private static javax.swing.JTextField emerContactNoField;
    private javax.swing.JLabel emerContactNoLabel;
    private static javax.swing.JTextField emerContactRelationshipField;
    private javax.swing.JLabel emerContactRelationshipLabel;
    private javax.swing.JPanel emerContactSection;
    private static javax.swing.JLabel genderLabel;
    private static javax.swing.JLabel hpNoLabel;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private static javax.swing.JTextField medCondField;
    private static javax.swing.JLabel nameLabel;
    private static javax.swing.JTextField nationalityField;
    private static javax.swing.JLabel nationalityLabel;
    private static javax.swing.JTextField raceField;
    private static javax.swing.JTextField religionField;
    private javax.swing.JPanel roomDetailsSection;
    private static javax.swing.JLabel roomNumLabel;
    private static javax.swing.JLabel roomNumLabel1;
    private static javax.swing.JLabel roomTypeLabel;
    private javax.swing.JScrollPane scrollPane;
    private static javax.swing.JTextField startDateField;
    private javax.swing.JLabel startDateLabel;
    private static javax.swing.JComboBox<String> stayPeriodComboBox;
    private javax.swing.JPanel studentDetailsSection;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
