/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DesignUI;

import Models.Application;
import Models.Payment;
import Models.Room;
import Utils.PaymentHandling;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 *
 * @author KZ
 */
public class HomeST extends javax.swing.JPanel {
    
    private static String roomNumLabel, servicingLabel, checkInDateLabel, checkOutDateLabel;
    
    private static final DateTimeFormatter PAYMENT_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static String paymentStatus = "N/A";
    private static String paymentDueDate = "N/A";
    private static double paymentAmountDue = 0;
    private static double paymentAmountPayable = 0;
    
    /**
     * Creates new form HomeST
     */
    public HomeST() {
        initData();
        initComponents();
    }

    private static void initData() {
        Application application = HostelST.getCurrentUserApplication();
        Room room = HostelST.getCurrentUserRoom();
        if (room == null) {
            roomNumLabel = "N/A";
            servicingLabel = "N/A";
            checkInDateLabel = "N/A";
            checkOutDateLabel = "N/A";
        } else {
            roomNumLabel = room.getRoomID();
            if (room.isServicing()) {
                servicingLabel = "Yes";
            } else {
                servicingLabel = "No";
            }
            checkInDateLabel = application.getStartDate().split("\\?")[0];
            checkOutDateLabel = application.getEndDate().split("\\?")[0];
        }
    }
    
    private static void initPaymentData() {
        LocalDate now = LocalDate.now();
        ArrayList<Payment> userPayments = PaymentHandling.getCurrentStudentPayments(HostelST.getCurrentUser());
        Application application = userPayments.get(0).getApplication();
        LocalDate startDate = application.getLocalStartDate().toLocalDate();

        for (int i = 0; i < userPayments.size(); i++) {
            Payment payment = userPayments.get(i);
            LocalDate dueDate = startDate.plusMonths(i + 1).plusDays(7);

            if (payment.getPaymentStatus().equals("Overdue")) {
                paymentAmountDue += payment.getAmount();
                if (paymentDueDate.equals("N/A")) {
                    paymentStatus = "Overdue";
                    paymentDueDate = dueDate.format(PAYMENT_FORMATTER);
                }
            } else if (! paymentStatus.equals("Overdue")
                    && now.isAfter(dueDate.minusDays(7))
                    && now.isBefore(dueDate)
                    && payment.getPaymentStatus().equals("Pending")) {
                paymentStatus = "Pending";
                paymentDueDate = dueDate.format(PAYMENT_FORMATTER);
                paymentAmountDue += payment.getAmount();
            }

            if (!payment.getPaymentStatus().equals("Paid")) {
                paymentAmountPayable += payment.getAmount();
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        overviewPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        roomNum = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        servicing = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        checkInDate = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        checkOutDate = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        applicationStatus = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        paymentBtn = new javax.swing.JToggleButton();
        reApplyBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(930, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Overview");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 38));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 918, 10));

        overviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        overviewPanel.setLayout(new java.awt.GridLayout(3, 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Room Number");

        roomNum.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        roomNum.setForeground(new java.awt.Color(0, 0, 0));
        roomNum.setText(roomNumLabel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(roomNum)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(roomNum)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        overviewPanel.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Servicing");

        servicing.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        servicing.setForeground(new java.awt.Color(0, 0, 0));
        servicing.setText(servicingLabel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(servicing, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(servicing)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        overviewPanel.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Check-in Date");

        checkInDate.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        checkInDate.setForeground(new java.awt.Color(0, 0, 0));
        checkInDate.setText(checkInDateLabel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(checkInDate))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(checkInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        overviewPanel.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Check-out Date");

        checkOutDate.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        checkOutDate.setForeground(new java.awt.Color(0, 0, 0));
        checkOutDate.setText(checkOutDateLabel);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(checkOutDate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(checkOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        overviewPanel.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Application Status");

        applicationStatus.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        applicationStatus.setForeground(new java.awt.Color(0, 0, 0));
        applicationStatus.setText(HostelST.getCurrentUserApplication().getStatus());
        if (applicationStatus.getText().equals("Pending")) {
            applicationStatus.setForeground(Color.BLUE);
        } else if (applicationStatus.getText().equals("Rejected")) {
            applicationStatus.setForeground(Color.RED);
        } else {
            applicationStatus.setForeground(Color.GREEN);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(applicationStatus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(applicationStatus)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        overviewPanel.add(jPanel6);

        add(overviewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 66, 507, 440));

        paymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Payment Status");
        jPanel1.add(jLabel12);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText(paymentStatus);
        jPanel1.add(jLabel16);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Due Date");
        jPanel1.add(jLabel14);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText(paymentDueDate);
        jPanel1.add(jLabel18);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel19.setText("Amount Due");
        jPanel1.add(jLabel19);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("RM" + paymentAmountDue);
        jPanel1.add(jLabel20);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setText("<html>Total Amount <br/>Payable</html>");
        jPanel1.add(jLabel15);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setText("RM" + paymentAmountPayable);
        jPanel1.add(jLabel17);

        paymentPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 320, 320));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/usd-circle.png"))); // NOI18N
        jLabel13.setText("  Payment");
        paymentPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, -1));

        paymentBtn.setBackground(new java.awt.Color(0, 0, 0));
        paymentBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        paymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        paymentBtn.setText("Proceed to Payment");
        paymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentBtnActionPerformed(evt);
            }
        });
        paymentPanel.add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        add(paymentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 66, 363, 440));

        reApplyBtn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        reApplyBtn.setText("Re-apply");
        reApplyBtn.setToolTipText("");
        reApplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reApplyBtnActionPerformed(evt);
            }
        });
        add(reApplyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 120, 30));
        if (applicationStatus.getText().equals("Rejected")) {
            reApplyBtn.setVisible(true);
        } else {
            reApplyBtn.setVisible(false);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void paymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentBtnActionPerformed
        // TODO add your handling code here:
        HostelST.showPayment();
    }//GEN-LAST:event_paymentBtnActionPerformed

    private void reApplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reApplyBtnActionPerformed
        // TODO add your handling code here:
        HostelST.showRooms();
    }//GEN-LAST:event_reApplyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicationStatus;
    private javax.swing.JLabel checkInDate;
    private javax.swing.JLabel checkOutDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JToggleButton paymentBtn;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JButton reApplyBtn;
    private javax.swing.JLabel roomNum;
    private javax.swing.JLabel servicing;
    // End of variables declaration//GEN-END:variables
}
