// @author Brandon Ban Kai Xian TP067094
package DesignUI;

import Models.Application;
import Models.Room;
import Models.RoomType;
import Utils.ApplicationHandling;
import Utils.RoomHandling;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class MonthlyIncome extends javax.swing.JFrame {
    private final ArrayList<Application> totalApplications = ApplicationHandling.getTotalApplications();
    private String yearSelect, monthSelect;
    private boolean checkDate = false;
    /**
     * Creates new form MonthlyIncome
     */
    public MonthlyIncome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateGeneratedBox = new javax.swing.JTextField();
        totalRevenueBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        monthDropBox = new javax.swing.JComboBox<>();
        yearBox = new javax.swing.JTextField();
        generateReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Monthly Income");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 40)); // NOI18N
        jLabel1.setText("Monthly Income Report");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        jLabel2.setText("Hotel Name:            JomStay Hotel");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        jLabel3.setText("Year:");

        dateGeneratedBox.setEditable(false);
        dateGeneratedBox.setBackground(new java.awt.Color(255, 255, 255));
        dateGeneratedBox.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        dateGeneratedBox.setText("-");
        dateGeneratedBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        totalRevenueBox.setEditable(false);
        totalRevenueBox.setBackground(new java.awt.Color(255, 255, 255));
        totalRevenueBox.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        totalRevenueBox.setText("-");
        totalRevenueBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        jLabel4.setText("Total revenue:");

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        jLabel5.setText("Date Generated:");

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 30)); // NOI18N
        jLabel6.setText("Month:");

        monthDropBox.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        monthDropBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "January", "Febraury", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        yearBox.setBackground(new java.awt.Color(255, 255, 255));
        yearBox.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        yearBox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));

        generateReportButton.setBackground(new java.awt.Color(153, 153, 255));
        generateReportButton.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        generateReportButton.setText("Generate Report");
        generateReportButton.setBorder(null);
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(monthDropBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateGeneratedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalRevenueBox, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(44, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(monthDropBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateGeneratedBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalRevenueBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        showInForm();
    }//GEN-LAST:event_formComponentShown

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportButtonActionPerformed
        checkDate = true;
        showInForm();
    }//GEN-LAST:event_generateReportButtonActionPerformed
    
    private String convertMonth(String monthSelect) {
        switch(monthSelect){
            case "January" -> {
                return "01";
            }
            case "February" -> {
                return "02";
            }
            case "March" -> {
                return "03";
            }
            case "April" -> {
                return "04";
            }
            case "May" -> {
                return "05";
            }
            case "June" -> {
                return "06";
            }
            case "July" -> {
                return "07";
            }
            case "August" -> {
                return "08";
            }
            case "September" -> {
                return "09";
            }
            case "October" -> {
                return "10";
            }
            case "November" -> {
                return "11";
            }
            case "December" -> {
                return "12";
            }
            default -> {
                return "00";
            }
        }
    }
    
    private double getTotalRevenue(){
        ArrayList<Application> acceptedApplication = new ArrayList<>();
        double totalRevenue = 0;
        for(Application application : totalApplications){
            String startTime = application.getStartDate();
            String endTime = application.getEndDate();
            String[] startTimeSplit = startTime.split("-");
            String[] endTimeSplit = endTime.split("-");
            String compareStart = "" + startTimeSplit[0] + startTimeSplit[1];
            String compareEnd = "" + endTimeSplit[0] + endTimeSplit[1];
            String compareNow = "" + yearSelect + convertMonth(monthSelect);
            
            if(application.getStatus().equals("Accepted")){
                if(Integer.parseInt(compareNow) >= Integer.parseInt(compareStart) 
                        && Integer.parseInt(compareNow) <= Integer.parseInt(compareEnd)){
                    acceptedApplication.add(application);
                }
            }
        }
        for(Application application:acceptedApplication) {
            Room room = application.getRoom();
            RoomType searchRoomPrice = RoomHandling.matchRoom(room);
            totalRevenue += (searchRoomPrice.getRentalFee() / 12);
        }
        
        return totalRevenue;
    }
    
    private void showInForm() {
        if(checkDate){
            LocalDateTime currentLocalDateTime = LocalDateTime.now();
            DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            String dateTime = currentLocalDateTime.format(dateTimeFormatter);
            yearSelect = yearBox.getText();
            monthSelect = (String) monthDropBox.getModel().getSelectedItem();
            if (yearSelect.equals("") || monthSelect.equals("Select")){
                JOptionPane.showMessageDialog(
                        null, 
                        "Please ensure you've fill in every text field", 
                        "Friendly Reminder", 
                        JOptionPane.QUESTION_MESSAGE);
            } else {
                dateGeneratedBox.setText(dateTime);
                totalRevenueBox.setText(String.format("%.2f",getTotalRevenue()));
            }
        }
    }
    
    public void start(){
        new MonthlyIncome().setVisible(true);
        showInForm();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyIncome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MonthlyIncome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateGeneratedBox;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> monthDropBox;
    private javax.swing.JTextField totalRevenueBox;
    private javax.swing.JTextField yearBox;
    // End of variables declaration//GEN-END:variables
}
